# Generated by Django 5.1.1 on 2024-09-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebooklink', models.URLField()),
                ('instagramlink', models.URLField()),
                ('yotubelink', models.URLField()),
                ('linkedlnlink', models.URLField()),
            ],
        ),
    ]
