# Generated by Django 5.1.1 on 2024-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bloimage/')),
                ('hotelname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AT', 'Apartment'), ('VA', 'Vila'), ('HE', 'Home'), ('OE', 'Office'), ('BG', 'Building'), ('TE', 'Townhouse'), ('SP', 'Shop'), ('GE', 'Grage')], max_length=50)),
                ('image', models.ImageField(upload_to='propertytype/')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AT', 'Apartment'), ('VA', 'Vila'), ('HE', 'Home'), ('OE', 'Office'), ('BG', 'Building'), ('TE', 'Townhouse'), ('SP', 'Shop'), ('GE', 'Grage')], max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
