# Generated by Django 5.1.1 on 2024-09-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AT', 'Apartment'), ('VA', 'Vila'), ('HE', 'Home'), ('OE', 'Office'), ('BG', 'Building'), ('TE', 'Townhouse'), ('SP', 'Shop'), ('GE', 'Grage')], max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='imagehotel/')),
                ('address', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
            ],
        ),
    ]
